openapi: 3.0.4
info:
  title: Backpacks API
  description: |-
    This is a sample OpenAPI 3.0 specification for an API related to Backpacks.

    This API has not been implemented. This specification is purely for the use in Izzi's talk for OpenAPI 3.0 specifications.

    Backpacks may or may not be filled with soap.
  termsOfService: https://swagger.io/terms/
  contact:
    name: Izzi Bikun
    email: izzi.bikun@backpacks.com
    url: https://www.linkedin.com/in/elizabethbikun/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Learn more about SOAP
  url: https://a.co/d/7VYsu4v
servers:
  - url: https://wwww.the-store.com
tags:
  - name: Backpacks
    description: I'm going on an adventure!
  - name: Items
    description: It's dangerous to go alone. Take this.
paths:
  /backpacks:
    get:
      tags:
        - Backpacks
      summary: Retrieve Backpacks.
      description: Retrieve all backpacks in the store.
      parameters:
        - name: id
          in: query
          description: Backpack ids to filter by. Multiple IDs can be sent as a comma separated list.
          required: false
          schema:
            $ref: '#/components/schemas/UUID'
        - name: X-Tracing-Id
          in: header
          description: ID used to traces calls through the stack.
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: Backpacks have successfully been retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  backpacks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Backpack'
    post:
      tags:
        - Backpacks
      summary: Create Backpack
      description: Add a new backpack to the store.
      requestBody:
        required: true
        description: Information about the backpack being created. All backpacks are created as empty backpacks without any items in them. 
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the backpack.
      responses:
        200:
          description: Backpacks have successfully been retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: '#/components/schemas/UUID'
                  name:
                    type: string
                    description: The name of the backpack.
  /backpacks/{id}:
    get:
      tags:
        - Backpacks
      summary: Retrieve specific backpack
      description: Retrieve a singular backpack by the id of the backpack.
      parameters:
        - name: id
          in: path
          description: Backpack ids to filter by.
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
        - name: X-Tracing-Id
          in: header
          description: ID used to traces calls through the stack.
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: Backpack has successfully been retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Backpack'
    patch:
      tags:
        - Backpacks
      summary: Update specific backpack.
      description: Update a specific backpack. Items can be removed from a backpack by setting their quanity to zero. 
      parameters:
        - name: id
          in: path
          description: Backpack ids to filter by.
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
        - name: X-Tracing-Id
          in: header
          description: ID used to traces calls through the stack.
          schema:
            $ref: '#/components/schemas/UUID'
      requestBody:
        required: true
        description: The information about the backpack that needs updating. Only fields that need updated should be sent in the request body.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Backpack'
      responses:
        200:
          description: Backpack has successfully been updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Backpack'
    delete:
      tags:
        - Backpacks
      summary: Delete specific backpack.
      description: Delete a specific backpack. Deletes are soft deletes.
      parameters:
        - name: id
          in: path
          description: Backpack ids to filter by.
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
        - name: X-Tracing-Id
          in: header
          description: ID used to traces calls through the stack.
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        204:
          description: Backpack has successfully been deleted.
  /items:
    get:
      tags:
        - Items
      summary: Retrieve Items.
      description: Retrieve all items in the store.
      parameters:
        - name: id
          in: query
          description: Item ids to filter by. Multiple IDs can be sent as a comma separated list.
          required: false
          schema:
            $ref: '#/components/schemas/UUID'
        - name: X-Tracing-Id
          in: header
          description: ID used to traces calls through the stack.
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: Items have successfully been retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  backpacks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Item'
    post:
      tags:
        - Items
      summary: Create Item
      description: Add a new item to the store.
      requestBody:
        required: true
        description: Information about the item being created.
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the item.
                weight:
                  type: integer
                  description: The weight of the item in grams.
      responses:
        200:
          description: Items have successfully been retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  /items/{id}:
    get:
      tags:
        - Items
      summary: Retrieve specific item
      description: Retrieve a singular item by the id of the item.
      parameters:
        - name: id
          in: path
          description: Item ids to filter by.
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
        - name: X-Tracing-Id
          in: header
          description: ID used to traces calls through the stack.
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: Item has successfully been retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    patch:
      tags:
        - Items
      summary: Update specific item.
      description: Update a specific item.
      parameters:
        - name: id
          in: path
          description: Item ids to filter by.
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
        - name: X-Tracing-Id
          in: header
          description: ID used to traces calls through the stack.
          schema:
            $ref: '#/components/schemas/UUID'
      requestBody:
        required: true
        description: The information about the item that needs updating. Only fields that need updated should be sent in the request body.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        200:
          description: Item has successfully been updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    delete:
      tags:
        - Items
      summary: Delete specific item.
      description: Delete a specific item. Deletes are soft deletes.
      parameters:
        - name: id
          in: path
          description: Item ids to filter by.
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
        - name: X-Tracing-Id
          in: header
          description: ID used to traces calls through the stack.
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        204:
          description: Item has successfully been deleted.
components:
  schemas:
    Backpack:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        name:
          type: string
          description: The name of the backpack.
        items:
          description: This items contained inside the backpack.
          type: array
          items:
            type: object
            properties:
              id:
                $ref: '#/components/schemas/UUID'
              quantity:
                type: integer
                description: The amount of the item in the backpack.
    Item:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        name:
          type: string
          description: The name of the item.
        weight:
          type: integer
          description: The weight of the item in grams.
        associatedItem:
          $ref: '#/components/schemas/Item'
    UUID:
      type: string
      format: UUID
      description: The unique identifier
      example: 1e3386b3-5472-4caa-99ff-2615f86aa108
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            "write:pets": modify pets in your account
            "read:pets": read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header